### ISSUE TITLE
Postproccommand does not run

### ISSUE THREAD

**Issue by basbossink** [jgoerzen/hpodder#1]
Given the following hpodder.conf:

<pre>    
[general]

; The following line tells hpodder that
; you have already gone through the intro.
showintro = no
postproctype = ALL
postproccommand = echo "Running post proc command on ${EPFILENAME}"
</pre>

After performing: 

`hpodder add http://www.bnr.nl/radio/columns/kort/?view=Podcast`

the content of fetch.log after the following command line:

```
hpodder -d fetch > fetch.log 2>&1 &
```

does not contain any text "Running post proc command" while an episode of the above mentioned podcast is downloaded successfully.

Looking at the code of Commands/Downloads.hs I would expect to see some output and of course my proccommand to be run.

**Comment by jgoerzen** [comment]
Looks like a typo.  You should have "postproctypes" instead of "postproctype."
